/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { PimmsError } from "./pimmserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * A short code indicating the error code returned.
 */
export const InviteExpiredCode = {
  InviteExpired: "invite_expired",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type InviteExpiredCode = ClosedEnum<typeof InviteExpiredCode>;

export type InviteExpiredError = {
  /**
   * A short code indicating the error code returned.
   */
  code: InviteExpiredCode;
  /**
   * A human readable explanation of what went wrong.
   */
  message: string;
};

/**
 * This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
 */
export type InviteExpiredData = {
  error: InviteExpiredError;
};

/**
 * This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
 */
export class InviteExpired extends PimmsError {
  error: InviteExpiredError;

  /** The original data that was passed to this error instance. */
  data$: InviteExpiredData;

  constructor(
    err: InviteExpiredData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "InviteExpired";
  }
}

/** @internal */
export const InviteExpiredCode$inboundSchema: z.ZodNativeEnum<
  typeof InviteExpiredCode
> = z.nativeEnum(InviteExpiredCode);
/** @internal */
export const InviteExpiredCode$outboundSchema: z.ZodNativeEnum<
  typeof InviteExpiredCode
> = InviteExpiredCode$inboundSchema;

/** @internal */
export const InviteExpiredError$inboundSchema: z.ZodType<
  InviteExpiredError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: InviteExpiredCode$inboundSchema,
  message: z.string(),
});
/** @internal */
export type InviteExpiredError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const InviteExpiredError$outboundSchema: z.ZodType<
  InviteExpiredError$Outbound,
  z.ZodTypeDef,
  InviteExpiredError
> = z.object({
  code: InviteExpiredCode$outboundSchema,
  message: z.string(),
});

export function inviteExpiredErrorToJSON(
  inviteExpiredError: InviteExpiredError,
): string {
  return JSON.stringify(
    InviteExpiredError$outboundSchema.parse(inviteExpiredError),
  );
}
export function inviteExpiredErrorFromJSON(
  jsonString: string,
): SafeParseResult<InviteExpiredError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InviteExpiredError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InviteExpiredError' from JSON`,
  );
}

/** @internal */
export const InviteExpired$inboundSchema: z.ZodType<
  InviteExpired,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => InviteExpiredError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InviteExpired(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InviteExpired$Outbound = {
  error: InviteExpiredError$Outbound;
};

/** @internal */
export const InviteExpired$outboundSchema: z.ZodType<
  InviteExpired$Outbound,
  z.ZodTypeDef,
  InviteExpired
> = z.instanceof(InviteExpired)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => InviteExpiredError$outboundSchema),
  }));
