/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { PimmsError } from "./pimmserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * A short code indicating the error code returned.
 */
export const RateLimitExceededCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type RateLimitExceededCode = ClosedEnum<typeof RateLimitExceededCode>;

export type RateLimitExceededError = {
  /**
   * A short code indicating the error code returned.
   */
  code: RateLimitExceededCode;
  /**
   * A human readable explanation of what went wrong.
   */
  message: string;
};

/**
 * The user has sent too many requests in a given amount of time ("rate limiting")
 */
export type RateLimitExceededData = {
  error: RateLimitExceededError;
};

/**
 * The user has sent too many requests in a given amount of time ("rate limiting")
 */
export class RateLimitExceeded extends PimmsError {
  error: RateLimitExceededError;

  /** The original data that was passed to this error instance. */
  data$: RateLimitExceededData;

  constructor(
    err: RateLimitExceededData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "RateLimitExceeded";
  }
}

/** @internal */
export const RateLimitExceededCode$inboundSchema: z.ZodNativeEnum<
  typeof RateLimitExceededCode
> = z.nativeEnum(RateLimitExceededCode);
/** @internal */
export const RateLimitExceededCode$outboundSchema: z.ZodNativeEnum<
  typeof RateLimitExceededCode
> = RateLimitExceededCode$inboundSchema;

/** @internal */
export const RateLimitExceededError$inboundSchema: z.ZodType<
  RateLimitExceededError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: RateLimitExceededCode$inboundSchema,
  message: z.string(),
});
/** @internal */
export type RateLimitExceededError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const RateLimitExceededError$outboundSchema: z.ZodType<
  RateLimitExceededError$Outbound,
  z.ZodTypeDef,
  RateLimitExceededError
> = z.object({
  code: RateLimitExceededCode$outboundSchema,
  message: z.string(),
});

export function rateLimitExceededErrorToJSON(
  rateLimitExceededError: RateLimitExceededError,
): string {
  return JSON.stringify(
    RateLimitExceededError$outboundSchema.parse(rateLimitExceededError),
  );
}
export function rateLimitExceededErrorFromJSON(
  jsonString: string,
): SafeParseResult<RateLimitExceededError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimitExceededError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimitExceededError' from JSON`,
  );
}

/** @internal */
export const RateLimitExceeded$inboundSchema: z.ZodType<
  RateLimitExceeded,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => RateLimitExceededError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RateLimitExceeded(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RateLimitExceeded$Outbound = {
  error: RateLimitExceededError$Outbound;
};

/** @internal */
export const RateLimitExceeded$outboundSchema: z.ZodType<
  RateLimitExceeded$Outbound,
  z.ZodTypeDef,
  RateLimitExceeded
> = z.instanceof(RateLimitExceeded)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => RateLimitExceededError$outboundSchema),
  }));
