/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { PimmsError } from "./pimmserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * A short code indicating the error code returned.
 */
export const UnauthorizedCode = {
  Unauthorized: "unauthorized",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type UnauthorizedCode = ClosedEnum<typeof UnauthorizedCode>;

export type UnauthorizedError = {
  /**
   * A short code indicating the error code returned.
   */
  code: UnauthorizedCode;
  /**
   * A human readable explanation of what went wrong.
   */
  message: string;
};

/**
 * Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
 */
export type UnauthorizedData = {
  error: UnauthorizedError;
};

/**
 * Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
 */
export class Unauthorized extends PimmsError {
  error: UnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedData;

  constructor(
    err: UnauthorizedData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "Unauthorized";
  }
}

/** @internal */
export const UnauthorizedCode$inboundSchema: z.ZodNativeEnum<
  typeof UnauthorizedCode
> = z.nativeEnum(UnauthorizedCode);
/** @internal */
export const UnauthorizedCode$outboundSchema: z.ZodNativeEnum<
  typeof UnauthorizedCode
> = UnauthorizedCode$inboundSchema;

/** @internal */
export const UnauthorizedError$inboundSchema: z.ZodType<
  UnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: UnauthorizedCode$inboundSchema,
  message: z.string(),
});
/** @internal */
export type UnauthorizedError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const UnauthorizedError$outboundSchema: z.ZodType<
  UnauthorizedError$Outbound,
  z.ZodTypeDef,
  UnauthorizedError
> = z.object({
  code: UnauthorizedCode$outboundSchema,
  message: z.string(),
});

export function unauthorizedErrorToJSON(
  unauthorizedError: UnauthorizedError,
): string {
  return JSON.stringify(
    UnauthorizedError$outboundSchema.parse(unauthorizedError),
  );
}
export function unauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<UnauthorizedError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnauthorizedError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnauthorizedError' from JSON`,
  );
}

/** @internal */
export const Unauthorized$inboundSchema: z.ZodType<
  Unauthorized,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => UnauthorizedError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new Unauthorized(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type Unauthorized$Outbound = {
  error: UnauthorizedError$Outbound;
};

/** @internal */
export const Unauthorized$outboundSchema: z.ZodType<
  Unauthorized$Outbound,
  z.ZodTypeDef,
  Unauthorized
> = z.instanceof(Unauthorized)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => UnauthorizedError$outboundSchema),
  }));
