/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Analytics } from "./analytics.js";
import { Links } from "./links.js";
import { QRCodes } from "./qrcodes.js";
import { Track } from "./track.js";

export class Pimms extends ClientSDK {
  private _links?: Links;
  get links(): Links {
    return (this._links ??= new Links(this._options));
  }

  private _analytics?: Analytics;
  get analytics(): Analytics {
    return (this._analytics ??= new Analytics(this._options));
  }

  private _track?: Track;
  get track(): Track {
    return (this._track ??= new Track(this._options));
  }

  private _qrCodes?: QRCodes;
  get qrCodes(): QRCodes {
    return (this._qrCodes ??= new QRCodes(this._options));
  }
}
