/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the pimms SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx linksCreate.example.ts
 */

import { Pimms } from "pimms";

const pimms = new Pimms({
  token: "PIMMS_API_KEY",
});

async function main() {
  const result = await pimms.links.create({
    url: "https://pimms.io",
    externalId: "123456",
    tagIds: [
      "clux0rgak00011...",
    ],
  });

  console.log(result);
}

main().catch(console.error);
